// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrA8JPu9MU8YfwvguB_q1G6FzpRMwV1ug',
    appId: '1:576730007031:web:2293150480da636c8c9af2',
    messagingSenderId: '576730007031',
    projectId: 'elderly-homecare-firebase',
    authDomain: 'elderly-homecare-firebase.firebaseapp.com',
    databaseURL: 'https://elderly-homecare-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderly-homecare-firebase.appspot.com',
    measurementId: 'G-D3NTVNXQ41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdbX_x400dI1G9UjTriZTL9PVGMxVGLTI',
    appId: '1:576730007031:android:2dd59af7225083158c9af2',
    messagingSenderId: '576730007031',
    projectId: 'elderly-homecare-firebase',
    databaseURL: 'https://elderly-homecare-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderly-homecare-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXR36Rek5E57K8n6YZhZQO0bBv8VNxV8Q',
    appId: '1:576730007031:ios:eb27fbd5acf64c4c8c9af2',
    messagingSenderId: '576730007031',
    projectId: 'elderly-homecare-firebase',
    databaseURL: 'https://elderly-homecare-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderly-homecare-firebase.appspot.com',
    iosBundleId: 'com.example.eldergit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXR36Rek5E57K8n6YZhZQO0bBv8VNxV8Q',
    appId: '1:576730007031:ios:35dd59cdadbacb4e8c9af2',
    messagingSenderId: '576730007031',
    projectId: 'elderly-homecare-firebase',
    databaseURL: 'https://elderly-homecare-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderly-homecare-firebase.appspot.com',
    iosBundleId: 'com.example.eldergit.RunnerTests',
  );
}
